config/routes.rb
RailsPresenterWithDraper::Application.routes.draw do
  resources :customers

  root       :to => "customers#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  def to_json
    # TODO
  end

end


# == Schema Information
#
# Table name: customers
#
#  id           :integer         not null, primary key
#  username     :string(255)
#  first_name   :string(255)
#  last_name    :string(255)
#  email        :string(255)
#  fon_country  :integer
#  fon_city     :integer
#  fon          :integer
#  twitter_name :string(255)
#  image        :string(255)
#  is_company   :boolean
#  created_at   :datetime
#  updated_at   :datetime
#  login        :boolean
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = CustomerDecorator.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(params[:customer])

    if @customer.save
      redirect_to(@customer, :notice => 'Customer was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update_attributes(params[:customer])
      redirect_to(@customer, :notice => 'Customer was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to(customers_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= form_for @customer do |f|
  -if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :fon_country
    = f.text_field :fon_country
  .field
    = f.label :fon_city
    = f.text_field :fon_city
  .field
    = f.label :fon
    = f.text_field :fon
  .field
    = f.label :twitter_name
    = f.text_field :twitter_name
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :is_company
    = f.check_box :is_company
  .field
    = f.label :login
    = f.check_box :login
  .actions
    = f.submit 'Save'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
%h1 Listing customers

%table
  %tr
    %th Username
    %th First name
    %th Last name
    %th Email
    %th Fon country city #
    %th Twitter name
    %th Image URI
    %th Is company
    %th Is logged in
    %th
    %th
    %th

  - @customers.each do |customer|
    %tr
      %td= customer.username
      %td= customer.first_name
      %td= customer.last_name
      %td= customer.email
      %td= "#{customer.fon_country} #{customer.fon_city} #{customer.fon}"
      %td= customer.twitter_name
      %td= customer.image
      %td= customer.is_company
      %td= customer.login
      %td= link_to 'Show', customer
      %td= link_to 'Edit', edit_customer_path(customer)
      %td= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.haml
.cus_bit

  .cus_head
    = @customer.headline

    .cus_img
      = @customer.image

  %dl
    %dt Full name:
    %dd= @customer.name

    %dt Email:
    %dd= @customer.email

    %dt Fon:
    %dd= @customer.phone_number

    %dt Twitter:
    %dd= @customer.twitter_link


.cus_nav
  = link_to 'List', customers_path
  \|
  = link_to 'Edit', edit_customer_path(@customer)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Presenter with Draper</title>
  <%= stylesheet_link_tag "scaffold.css" %>
  <%= stylesheet_link_tag "boilerplate.css" %>
  <%= stylesheet_link_tag "customer.css" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>